#! /bin/bash

echo "Hello"
grep 'Places' FormattedQuestions.txt |cut -d'|' -f1
if [[ $(find . -name FormattedQuestions.txt) ]]
then
    echo "Found"
else
    cat QuestionBank.txt >> FormattedQuestions.txt
    echo "Created copy of Questions."
fi
