#! /bin/bash

pushd Scores > /dev/null

COUNT=1

sed 1d High-Scores | while read -r LINE
do
        ((COUNT+=1))

        SCORE=$(echo $LINE | tr -dc '0-9')

        if [[ $1 -eq $SCORE ]]
        then
                sed -i ''"$COUNT"'i'"$2 - $1"'' High-Scores
                break

        elif [[ $1 -lt $SCORE ]]
        then
                :
        elif [[ $1 -gt $SCORE ]]
        then
                sed -i ''"$COUNT"'i'"$2 - $1"'' High-Scores
                break
        fi

done

popd > /dev/null

